# Generated by Django 4.1.3 on 2022-12-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_photo_alter_book_image_and_more'),
        ('catalog', '0005_alter_author_photo_alter_book_image_and_more'),
    ]

    operations = [
    ]
