# Generated by Django 4.1.3 on 2022-12-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_products'),
        ('cart', '0003_alter_cart_products'),
    ]

    operations = [
    ]
